default: &default
  adapter: postgresql
  encoding: unicode
  database: dsbn-resource-booking-dev
  username: postgres
  password: simcoesignout
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# To setup rails, install and configure postgres, then run:
# rails db:setup and/or rails db:create
# then run rails db:migrate
development:
  <<: *default
  database: dsbn-resource-booking-dev
  username: postgres
  password: simcoesignout

test:
  <<: *default
  database: dsbn-resource-booking-test
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: srv-captain--dsbn-postgres
  port: 5432

production:
  <<: *default
  database: dsbn-resource-booking
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: srv-captain--dsbn-postgres
  port: 5432
