name: Build and Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-backend:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stagin'

    steps:
      - uses: actions/checkout@v3

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            ./
            captain-definition
          outPath: deploy.tar

      - uses: caprover/deploy-from-github@main
        with:
          server: '${{ secrets.CAPROVER_SERVER_BACKEND_STAGING }}'
          app: '${{ secrets.APP_NAME_BACKEND_STAGING }}'
          token: '${{ secrets.APP_TOKEN_BACKEND_STAGING }}'
